language: java
jdk: openjdk8
install: true
jobs:
  include:
    - stage: starter
      name: "Jupiter Starter Sample: Maven & Kotlin (JDK 1.8)"
      script: cd $TRAVIS_BUILD_DIR && ./mvnw -f ./pom-java8.xml test
    - stage: starter
      name: "Jupiter Starter Sample: Maven & Kotlin (JDK 11)"
      jdk: openjdk11
      script: cd $TRAVIS_BUILD_DIR && ./mvnw test
    - stage: starter
      name: "Jupiter Starter Sample: Maven & Kotlin (JDK 1.8) versions update"
      script: cd $TRAVIS_BUILD_DIR && ./mvnw -f ./pom-java8.xml versions:display-property-updates
    - stage: starter
      name: "Jupiter Starter Sample: Maven & Kotlin (JDK 11) versions update"
      jdk: openjdk11
      script: cd $TRAVIS_BUILD_DIR && ./mvnw versions:display-property-updates
cache:
  directories:
    - ~/.m2
